defmodule Paperhub.Repo.Migrations.AddUsersProjectsRelation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :name, :text
      add :bio, :text
      add :avatar, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:projects) do
      add :owner_id,
          references(:users,
            column: :id,
            name: "projects_owner_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:project_collaborators, primary_key: false) do
      add :role, :text

      add :project_id,
          references(:projects,
            column: :id,
            name: "project_collaborators_project_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :collaborator_id,
          references(:users,
            column: :id,
            name: "project_collaborators_collaborator_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:project_collaborators, "project_collaborators_project_id_fkey")

    drop constraint(:project_collaborators, "project_collaborators_collaborator_id_fkey")

    drop table(:project_collaborators)

    drop constraint(:projects, "projects_owner_id_fkey")

    alter table(:projects) do
      remove :owner_id
    end

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :avatar
      remove :bio
      remove :name
    end
  end
end
